# Generic ROS1 raw GNSS stream decoder.
# format: ubx | sbf | novatel | oem3 | rtcm3
format: ubx

# stream_type: serial | file | tcp_client | ntrip_client
stream_type: serial

# RTKLIB stream path examples:
# serial: /dev/ttyACM0:115200:8:n:1:off
# file:   /data/rover.ubx
# tcp:    192.168.1.10:3001
# ntrip:  user:password@caster.example.com:2101/MOUNT
stream_path: /dev/ttyACM0:115200:8:n:1:off

# RTKLIB receiver-dependent decoder options, if required.
receiver_option: ""

frame_id: gnss_receiver
use_gps_timestamp: false
poll_period_ms: 10

observation_topic: /gnss/observation
ephemeris_topic: /gnss/ephemeris
station_topic: /gnss/station_ecef
